import datetime
a=datetime.datetime.now()
print("answer a-->",a)
b=a.strftime("%Y")
print("answer b-->",b)
c=a.strftime("%B")
print("answer c-->",c)
d=a.strftime("%w")
print("answer d-->",d,"(here 0:sunday,6:saturday)")
e=a.strftime("%j")
print("answer e-->",e)
f=a.strftime("%d")
print("answer f-->",f)
g=a.strftime("%A")
print("answer g-->",g)
