a=int(input('Enter the first number '))
b=int(input('Enter the second number '))
print('Addition of',a,'and',b ,'is', a+b)
print('Subtraction of',a,'and',b ,'is', a-b)
print('Multiplication of',a,'and',b ,'is', a*b)
print('Divide of',a,'and',b ,'is', a/b)
